services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - postgres-network

  reporting_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reporting_app
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
    networks:
      - postgres-network
    command: [ "--config", "/config.yaml" ]

volumes:
  pg_data:

networks:
  postgres-network:
    driver: bridge