openapi: 3.0.0
info:
  title: Human Native AI Service API
  description: API for reporting data violations
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  /reports:
    get:
      summary: List all reports
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of reports
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    dataset_id:
                      type: integer
                    name:
                      type: string
                    type:
                      type: integer
                    reason:
                      type: string
    post:
      summary: Create a new report
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dataset_id:
                  type: integer
                name:
                  type: string
                type:
                  type: integer
                reason:
                  type: string
              required:
                - dataset_id
                - name
                - type
                - reason
      responses:
        '201':
          description: Report created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  dataset_id:
                    type: integer
                  name:
                    type: string
                  type:
                    type: integer
                  reason:
                    type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
